{% set name = "python-lsp-server" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67473bb301f35434b5fa8b21fc5ed5fac27dc8a8446ccec8bae456af52a0aef6

build:
  number: 0
  skip: True  # [py<38]
  # flake8 is unavailable for python versions less than 3.8.
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pylsp = pylsp.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2.0
    - setuptools_scm >=3.4.3
    - wheel
  run:
  # Required Dependencies
    - python
    - jedi >=0.17.2,<0.19.0
    - python-lsp-jsonrpc >=1.0.0
    - pluggy >=1.0.0
    - docstring-to-markdown
    - ujson >=3.0.0
    - setuptools >=39.0.0
  # Optional Dependencies
    - autopep8 >=1.6.0,<1.7.0
    - flake8 >=5.0.0,<7.0.0
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle =2.10.0
    - pydocstyle >=6.3.0,<6.4.0
    - pyflakes >=2.5.0,<3.1.0
    - pylint >=2.5.0,<3.0.0
    - rope >=1.2.0
    - toml
    - yapf <=0.32.0
    - whatthepatch >=1.0.2,<2.0.0

test:
  imports:
    - pylsp
  requires:
    - pip
  commands:
    - pylsp --help
    - python -m pip check || true  # [not win]
    - python -m pip check || exit 1  # [win]
    # this resolves the issue with flake 8 and importlib-metadata pinnings

about:
  home: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 3.6+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/python-lsp/python-lsp-server
  doc_url: https://github.com/python-lsp/python-lsp-server/blob/develop/README.md
extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - steff456
