{% set name = "python-lsp-server" %}
{% set version = "1.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 85fa090262c3d1aef09b759d98811d6cb9ad5bbc58af15d588608ae8c1925801

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pylsp = pylsp.__main__:main
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=69.0.0
    - setuptools-scm >=3.4.3
    - toml
  run:
    # Required Dependencies
    - python
    - docstring-to-markdown
    - importlib-metadata >=4.8.3  # [py<310]
    - jedi >=0.17.2,<0.21.0
    - pluggy >=1.0.0
    - python-lsp-jsonrpc >=1.1.0,<2.0.0
    - ujson >=3.0.0
    - black
    # Optional Dependencies - which have been included in our past releases
    - autopep8 >=2.0.4,<2.1.0
    - flake8 >=7.1,<8
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle >=2.12.0,<2.13.0  # [py<314]
    # pycodestyle updated source code to support Python 3.14 in version 2.14.0
    # https://github.com/PyCQA/pycodestyle/commit/ae41b3420360a9f6732b316f5746c56146a37932
    - pycodestyle ==2.14.0  # [py==314]
    - pydocstyle >=6.3.0,<6.4.0
    - pyflakes >=3.2.0,<3.3.0  # [py<314]
    # pyflakes updated source code to support Python 3.14 in version 3.4.0
    # https://github.com/PyCQA/pyflakes/commit/e5d4ba166d3b9236ba2ece8ae1c66a99752a5666
    - pyflakes ==3.4.0  # [py==314]
    - pylint >=3.1,<4.1
    - rope >=1.11.0
    - yapf >=0.33.0
    - whatthepatch >=1.0.2,<2.0.0
  run_constrained:
    - websockets >=10.3

test:
  source_files:
    - test
    - .pylintrc
  imports:
    - pylsp
    - pylsp.config
    - pylsp.plugins
  commands:
    - pip check
    - pylsp --help
    - pytest -v test -k "not (test_flake8_config_param or test_missing_message)"
  requires:
    - pip
    - pytest
    - numpy
    - pandas
    - matplotlib-base
    - pyqt >=6.5,<7
    - flaky
    - websockets >=10.3

about:
  home: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 3.8+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes, and YAPF.
  dev_url: https://github.com/python-lsp/python-lsp-server
  doc_url: https://github.com/python-lsp/python-lsp-server/blob/develop/README.md

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - steff456
  skip-lints:
    - python_build_tool_in_run
