{% set name = "python-lsp-server" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50ca0639b11a635cac42ff4334a3944a7a91361cf888489321a4273701ff9068

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pylsp = pylsp.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - jedi >=0.17.2,<0.19
    - python-lsp-jsonrpc >=1.0.0
    - pycodestyle >=2.7.0,<2.8.0
    - pydocstyle >=2.0.0
    - pyflakes >=2.3.0,<2.4.0
    - pylint >=2.5.0
    - python >=3.6
    - yapf
    - pluggy
    - autopep8
    - mccabe >=0.6.0,<0.7.0
    - setuptools >=39.0.0
    - rope >=0.10.5
    - flake8 >=3.8.0
    - ujson >=3.0

test:
  requires:
    - pip
  commands:
    - python -m pip check
    - pylsp --help

about:
  home: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 3.6+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/python-lsp/python-lsp-server

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - steff456
