{% set name = "python-lsp-server" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5c094c19925022a27c4068f414b2bb653243f8fb0d768e39735289d7a89380d

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pylsp = pylsp.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools >=39.0.0
    - setuptools_scm >=3.4.3
    - wheel
  run:
    # - importlib-metadata <4.3  # flake 8 requires an older version of importlib-metadata
    - autopep8 >=1.6.0,<1.7.0
    - flake8 >=4.0.0,<4.1.0
    - jedi >=0.17.2,<0.19.0
    - mccabe >=0.6.0,<0.8.0  # flake 8 requires a version less than 0.7.0
    - pluggy >=1.0.0
    - python-lsp-jsonrpc >=1.0.0
    - pycodestyle >=2.8.0,<2.9.0
    - pydocstyle >=2.0.0
    - pyflakes >=2.4.0,<2.5.0
    - pylint >=2.5.0
    - python
    - rope >=0.10.5
    - setuptools >=39.0.0
    - ujson >=3.0.0
    - yapf
    - whatthepatch

test:
  imports:
    - pylsp
  requires:
    - pip
  commands:
    - pylsp --help
    - python -m pip check

about:
  home: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 3.6+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/python-lsp/python-lsp-server
  doc_url: https://github.com/python-lsp/python-lsp-server/blob/develop/README.md
extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - steff456
