{% set name = "python-lsp-server" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: bfa3d6bbca3fc3e6d0137b27cd1eabee65783a8d4314c36e1e230c603419afa3

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pylsp = pylsp.__main__:main

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=69.0.0
    - setuptools_scm >=3.4.3
    - toml
  run:
  # Required Dependencies
    - python
    - docstring-to-markdown
    - importlib-metadata >=4.8.3  # [py<310]
    - jedi >=0.17.2,<0.20.0
    - pluggy >=1.0.0
    - python-lsp-jsonrpc >=1.1.0,<2.0.0
    - ujson >=3.0.0
    - black
  # Optional Dependencies - which have been included in our past releases
    - autopep8 >=2.0.4,<2.1.0
    - flake8 >=7.1,<8
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle >=2.12.0,<2.13.0
    - pydocstyle >=6.3.0,<6.4.0
    - pyflakes >=3.2.0,<3.3.0
    - pylint >=3.1,<4
    - rope >=1.11.0
    - yapf >=0.33.0
    - whatthepatch >=1.0.2,<2.0.0
  run_constrained:
    - websockets >=10.3

test:
  source_files:
    - test
    - .pylintrc
  imports:
    - pylsp
    - pylsp.config
    - pylsp.plugins
  commands:
    - pip check
    - pylsp --help
    - pytest -v test -k "not (test_flake8_config_param or test_missing_message)"
  requires:
    - pip
    - pytest
    - numpy
    - pandas
    - matplotlib-base
    - pyqt >=6.5,<7
    - flaky
    - websockets >=10.3

about:
  home: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 3.8+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/python-lsp/python-lsp-server
  doc_url: https://github.com/python-lsp/python-lsp-server/blob/develop/README.md

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - steff456
  skip-lints:
    - python_build_tool_in_run
